collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8763145
  brandStrength: 1
  lightness: 0.228697
  brandColors:
    - '#F3F3F3'
    - '#C5BDB2'
    - '#231419'
    - '#5F5764'
    - '#B4563A'
  rhythmicContrast: 0.2863292
typography_spectrum: 0.06750299
layout_spectrum: 0.9146079
name: NikkiVK
