layout_spectrum: 0.9146079
typography_spectrum: 0.06176154
color:
  saturation: 0.8763145
  lightness: 0.228697
  brandStrength: 0.4742967
  rhythmicContrast: 0.2863292
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: NikkiVK
